MongoDB: 
  uri: "mongodb://USER:password@IP:27017/?authSource=admin"
  database: "crafteconomy"
Redis: 
  uri: "redis://:PASSWORD@IP:6379"
TAX_RATE: 0.05
DAO_ESCROW_ENDPOINT_SECRET: "some.secret.here"
REDIS_KEY_EXPIRE_TIME: 0
DEV_MODE: false
API_ENDPOINT: http://65.108.125.182:1317/
SERVER_WALLET_ADDRESS: craft10r39fueph9fq7a6lgswu4zdsg8t3gxlqd6lnf0
SIGNING_WEBAPP_LINK: http://65.108.71.66:8081/
TX_QUERY_ENDPOINT: "http://65.108.125.182:1317/cosmos/tx/v1beta1/txs/{TENDERMINT_HASH}"