# This is a basic workflow that is manually triggered

name: Minecraft Integration

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Compile minecraft integration
      run: |
        cd minecraft-integration/craft-integration
        mvn -B package --file pom.xml
          

          
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Java JDK
#        uses: actions/setup-java@v2.5.0
#        with:
#          distribution: 'temurin' # See 'Supported distributions' for available options
#          java-version: '17'
#      - name: compile tests
#        run: |
#          cd minecraft-integration/craft-integration-testing
#          mvn -B package --file pom.xml
#
          
          
# Reece, I'm not sure what else we will want here.  Treat it like a stub of proper integration testing.       
        
        
          
